on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build mod_wsgi-httpd packages"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Build mod_wsgi packages"
        run: python setup.py sdist && ls -las dist
      - name: "Store built packages"
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  tests:
    name: "Test mod_wsgi-httpd package"
    runs-on: "ubuntu-20.04"
    needs:
    - build
    steps:
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Download built packages"
        uses: actions/download-artifact@v2
        with:
            name: dist
            path: dist
      - name: "Update pip installation"
        run: python -m pip install --upgrade pip setuptools wheel
      - name: "Install mod_wsgi-httpd"
        run: python -m pip install --verbose dist/mod_wsgi-httpd-[0-9].*.tar.gz
      - name: "Check mod_wsgi-apxs"
        run: mod_wsgi-apxs -q BINDIR
